services:
  api:
    ports:
      - "8080:80"
    build:
      context: ./OlimpiadasAPI
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./OlimpiadasAPI
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./DatabaseScripts:/docker-entrypoint-initdb.d
